[compilers]
as = 'nasm'
cc = 'clang'
cxx = 'clang++'

[features]
use_pch = true

[flags]
cflags = '-march=native -std=c11 -O2 -pipe'
cxxflags = '-march=native -std=c++23 -O2 -pipe'
ldflags = '  -lfmt'

[paths]
external_libs = [ '-lpthread' ]
include_dirs = [ '-Iinclude' ]

[project]
build_dir = '.autocc_build'
name = 'a.out'