# AUTOCC 0.1.5
# CONFIGURATION FILE 'autocc.toml' IS WRITTEN BY AUTOCC v0.1.5, MAKE SURE YOU HAVE THE APPROPRIATE AUTOCC BUILD.
# COPYRIGHT (C) assembler-0 2025
[compilers]
as = 'nasm'
cc = 'clang'
cxx = 'clang++'

[features]
use_pch = true

[paths]
exclude_patterns = []
include_dirs = [ 'include' ]

[project]
build_dir = '.autocc_build'
default_target = 'autocc'

[[targets]]
cflags = '-DUSE_TUI -O3 -march=native -std=c++23'
cxxflags = '-DUSE_TUI -O3 -march=native -std=c++23'
exclude_patterns = []
external_libs = [
    '-lz',
    '-lpthread',
    '-lssl',
    '-lcrypto',
    '-lftxui-component',
    '-lftxui-dom',
    '-lftxui-screen',
    '-lfmt',
    '-lxxhash',
    '-lzstd',
    '-lm',
    '-lbrotlidec'
]
ldflags = ''
main_file = './autocc.cc'
name = 'autocc'
output_name = 'autocc'
sources = [
    './autocc.cc',
]

[[targets]]
cflags = '-O3 -march=native -std=c++23'
cxxflags = '-O3 -march=native -std=c++23'
exclude_patterns = []
external_libs = [
    '-lz',
    '-lpthread',
    '-lssl',
    '-lcrypto',
    '-lfmt',
    '-lxxhash',
    '-lzstd',
    '-lm',
    '-lbrotlidec'
]
ldflags = ''
main_file = './autocc.cc'
name = 'autocc_cli'
output_name = 'autocc'
sources = [
    './autocc.cc',
]


